baseURL = "https://qasimdev.github.io/"
languageCode = "en-us"
title = "Mohammad Qasim"
pageSize = 5
theme = "PaperMod"
sectionPagesMenu = "home"

[params]
  [params.homeInfoParams]
   
    Title = "Hey, I am Mohammad Qasim 👋"
    Content = """Hey there! ✨ I'm a Flutter & Android developer who loves building cool, high-performance apps. 
    Whether it’s a sleek UI or a complex backend, I enjoy turning ideas into smooth, scalable experiences. 
    Also, if you ever want to chat about thriller movies or hip-hop music, I’m all in!"""
    ProfilePicture = "https://media.licdn.com/dms/image/v2/D4E03AQFyCFvNya1icQ/profile-displayphoto-shrink_800_800/profile-displayphoto-shrink_800_800/0/1708272636597?e=1747267200&v=beta&t=AkYsLAYCFrakWAILwsF_mO0JzJ0UkO1EWMZ32OAl6_s"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:devmohdqasim@gmail.com"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/qasimxo/"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/qasim-xo"

  [[params.socialIcons]]
    name = "letterboxd"
    url = "https://letterboxd.com/qasimdx/"

  [[params.socialIcons]]
    name = "leetcode"
    url = "https://leetcode.com/u/qasimzexal/"

  [[params.socialIcons]]
    name = "twitter"
    url = "https://x.com/devqasim_"

[menu]
[[menu.main]]
  name = "Home" 
  url = '/' 
  weight = 1

[[menu.main]]
  name = 'Projects'
  url = '/projects'
  weight = 3
